define g = Character("Guard")
label chapter_2:
    scene black
    nvlNar "If a man spreads the word about his comrade, saying, “Everyone sodomizes him” and further, “I can prove the charges against you,” but he is unable to do so, they shall strike that man 50 blows with rods; moreover, he shall pay 3,600 shekels of lead."
    nvlNar "Luludân was well acquainted with the laws, even if they were of divine inspiration he still questioned all of them, not less than a month after he almost got fired, if it weren’t for his dedication…"
    nvlNar "Nabisin always told him to hold tight, things might get better in the future. Luludân wanted to protect Nabisin… no matter the cost."
# Lulu’s POV:
    scene bedroom_1 with dissolve
    "As Nabi slowly fell asleep, the night felt much colder and lonely." 
    "A thought came across Lulu’s mind, leading him to rise and sit in the same chair Nabisin was previously sobbing."
    "Guilt, because he had thought he dragged Nabisin along with him just to fuck up everything now."
    "Guilt, because he knew the consequences of liking the same sex letter by letter. Guilt because he couldn’t make it up, so a thought invaded his mind ..."
    "... to leave and never be seen again and to leave Nabisin alone. To leave and be imprisoned instead of Nabisin."
    "The feeling of something hammering his chest came; breathing felt heavy and frantic, and even so, he felt like a void was growing inside of him, almost engulfed by the same thing that Nabisin had gone through a few moments before."
    "Intrusive thoughts made everything much worse. Tears started to fall as Lulu almost ripped his ears. Then he snapped; he had to leave."
    scene house_n
    "Outside, the wind was piercing through his bones, causing an unbearable chill —the very same cold Nabisin would experience if he didn’t do something to remedy this." 
    scene market_n
    scene citynight
    "Running back to the palace, he had forgotten the way; each street felt unrecognizable; his thoughts became jumbled with voices and feelings of regret, guilt, and anxiety."
    "Crying was not enough; he had to do something to free his lover from them; he had the urge to beat them, crush them, and even set them ablaze, for he would do everything to protect his Nabi."
    "There was a sudden gush of air, and the ground felt like collapsing under him. No one heard it, but Lulu had tripped over his own feet."
    "The ground felt much less painful than all the feelings bubbling inside him; an unfamiliar sound echoed through his skull."
    "A dark liquid started to drip once he groggily stood up. "
    "Feeling pain, he groped the top of his head as if he knew what had happened." 
    "One of his antlers had broken, and the blood soaked his fur, mixing with tears; he was now feeling like things were starting to blur."
    "He didn’t know what happened from then on. Had he fallen? He limply walked towards a wall to rest. All he could remember was he had promised Nabisin would be protected. No matter what."
# Nab’s POV: transition 
    scene sun with dissolve
    "The day came, and with it, the early morning sounds of birds chirping and the nearby market slowly woke Nabisin up. Nabisin felt so alone; the side of the bed previously occupied by Lulu was cold and lacked his figure."
    "Still sluggish from the restless night, Nabisin realized the guards might have come for Lulu instead of him."
    "Panting and still half-dressed, he hopped out of bed quickly and started to leave."
    "He suddenly heard heavy footsteps coming. The door had been left ajar all night as if someone had fled the house."
    "Lulu! No, he wouldn’t do that!"
    "Nabisin pondered to himself. He was still unsure why he was alone and if that was the only explanation for why their house had been intact but devoid of Lulu."
# Guards:
    show house
    g   "“Nabisin of the temple, come down immediately!”"
    "The guards’ voices hit like a hammer. Nabisin, completely frightened of what would happen, stood still, staring at the window, thinking of whether he should do something crazy."
    "Instead, he complied with the orders, as any more offense to the guards other than making them wait meant costly fees, or far worse, death. They waited for Nabisin to appear."
    "Their faces were stoic, distant, and demanding authority, and by the time Nabisin was close enough, they pulled him by his arms and dragged him to the outside."
    "The sunlight hit Nabisin in the eyes, temporarily blurring his vision. However, once everything started making sense again, some folks looked down on him some expecting this to happen, others worried about Nabisin’s fate from now on."
    "The day’s heat struck him. A damp sensation soaked some of his garments, and the heavy cuffs made his wrists ache. The heavy bronze was abrasive, wounding Nabisin’s fragile flesh. "
    "Everyone’s eyes were sharp upon him, as if hundreds of thorns were penetrating his skin while trudging through an unkempt garden.
    Occasionally their gazes averted back to their own business." 
    "Not long after, children that Nabisin recognized and some he even used to play with disappeared into the safety of the walls of their homes."
    "It was uncommon for someone to be imprisoned so early in the morning, as a priest’s daily duties were to give offerings to the gods.
    Space and time melded together." 
    "The palace’s streets, arches, and patios became a hot mess to Nabisin. All he could think about was Lulu and what could have become of him."
    "Attempts to free himself from the guards’ tight hold proved futile. The path that was once familiar to Nabisin became the very reason why he wanted to stray away from it. He yearned to go back home, and clung to fleeting hope that the gods had spared Lulu."
    "…"
# Lulu’s POV:
    "Morning came and went. Had he fallen or got carried by someone else? Was he buried under dirt mistaken for a body? It was a complex matter to discern at the moment."
    "Lulu opened his eyes. He found himself in a dark space. A ray of sunlight seeped through a window open just enough that he could look up at the figure that he assumed had taken upon his weight and put him on the bed."
# ???
    "???" "“Ah! You’re finally awake.”"
    "Trying to stand up, he almost fell again."
# ???
    "???" "“No, please stay put, you’re too much hurt to move.”"
    "???" "“I found you sprawled out upon the ground a couple of hours ago.”"
    "???" "“...I think someone must have stolen your antler. Just before I arrived it was still there, but once I made my way to your unconscious body it was nowhere to be found.”"
    "Sitting on the stiff bed frame, Lulu started to recount all the events that led him to his fate."
    "Falling on the ground, breaking his antler, getting lost in the night…"
    "... Leaving Nabby behind."
    "Once those last thoughts echoed through his mind, tears matted his fur as he lifted his hands to cover his face. Anger boiled inside of him like an erupting volcano. He was full of guilt for loving Nabisin, and guilt he had abandoned him for such a petty reason, and he had failed miserably to even to do that."
    "Thoughts simmered in Lulu’s head as he tried to hide his shame."
    "I’m a failure, I’m a failure, I’m a failure…"
    "No one can fix what I’ve done. I’ve brought this upon myself and Nabisin. I just wish it could be just us. I wish things could’ve been easier. I wish things would work out as everyone says."
    "Why must they bother us? We never did anything to deserve this persecution. We were always there to help people, but what if we were always the problem?"
    "A sea of regret washed over Luludân. Every sound became white noise drowned in a dense liquid. He wanted to go back and profusely apologize to Nabisin, saying he was sorry ... sorry for everything."
    "With muzzle buried in his hands, still sobbing, he tried to raise his voice but barely could make audible sounds; under his uncontrolled breath, he winced."
# Luludân:
    l   "“I’m so sorry Nabby… I shouldn’t have never...d-, do- ... -ne that…”"
    "I shouldn’t have kept things so secretive that day we first met. If only I had been open then, maybe we wouldn’t be treading on eggshells now."
    "For inebriating the details, hiding behind my facade, and pretending nothing would happen to us ... I was so naive and couldn’t bear you knowing and hating me for it."
    "I hope you don’t have such a distorted image of me because of all my inconsistencies over the years."
    "I just needed time to tell you. Now, it may never manifest into reality."
    "Amidst the chaos in Lulu’s mind, his surroundings were reduced to black cloth, threatening to choke him as time passed."
    "Suddenly, a noise distracted him from his sorrowful whimpers and flood of tears."
    "He suddenly found himself at what had once been an unfamiliar place to Lulu, but now it felt familiar."
    "Looking even closer, adjusting his eyes to the amount of light coming off the window to his back, he noticed something odd, or rather, something he knew all too well."
    "That’s when he realized he had been at his house the entire time and that his mysterious savior was also long gone."
    "Maybe if he hadn’t wept like a toddler, they would have remained there, but on more pressing matters."
    "Lulu had to recompose himself as the environment he found himself in was coming together with memories."
    "Tears came back rolling, but not of melancholy but of happiness. Had Nabisin prayed for Lulu to find his way out? Lulu was convinced he had to do something to fix his wrongdoings."
    "…"
# Nabby POV:
# [day 1]
    scene prison with dissolve 
    "Moist, stale air awaited Nabisin inside the prison the kings had designed to hold hardened criminals. Rarely was someone imprisoned there; house arrest was much preferred for less sensitive cases."
    "Yet, Nabisin had been an essential priest for many years, having escaped servitude under the current reign of King Shulgi."
    "Needless to say, it’s a sensitive case. Perhaps any further ruckus would lead the populace to question the authority and resolve of the king. He likely needed to care of Nabisin before more rumors went astray."
    "It is not a king’s perogative to execute the punishment, but rather that of judges and other scribes; through his connections, perhaps Lulu could help Nabisin, but that is for the future to decide."
    "The worst part of this entire avail is Nabisin’s compliance. He knew something like this could happen, but he wasn’t expecting it to happen from his carelessness for raising his voice in defence at a banquet."
    "If being executed would give a solid end to his life, this was only the beginning of his downfall. If the gods had blessed his people, why of all things do so many narrowminded people harass him?"
    "No response came."
    "He was expecting this, but now, dwelling in these thoughts and surrendering to his fate, Nabisin had to do something ... Anything, really."
    "Wait, what was his response?"
    "Waiting for when the tides would become more favorable? Was acting on impulse is the best choice? Praying was the only activity he could think of to ease his mind."
    "How many days have gone by? He couldn’t be sure, but they usually treated cases like these quickly. He could be executed or exiled, beaten or pay exhorbant fees of many shekels..."
# … [day 3]
    "One day and one night could have went by, or three weeks, even three moons. Time became meaningless being there. Had his lover forgotten him yet?"
    "No!"
    "Nabisin almost yelled in response to his intrusive thought."
    "His throat was coarse, his appearance disheveled and all hygiene was neglected. He truly felt alone, thoughts burbling and throttling. Nabisin swore he was drowning."
    "Guards came in and out, but no sign or news of Lulu. Nabisin thought of many possibilities, but even standing became a difficult task. The ceiling felt as if it were slowly closing down upon him."
    "Nabisin had never feared tight spaces, but newfound claustrophobia surfaced due to his current situation."
    "Unsure of how far the prison was from his house or the city of Ur, he wondered how his neighbors were living in his absence."
    "He used to cherish the little neighborhood he lived in."
    "He was playful with the children and empathetic with the sick who had called his service to bring cures and blessings..."
    "The cold ground and rancid stench of his cell rudely booted Nabisin from his memories back to reality."
    "He missed the freshness of his special someone, someone he cares for and longs for, but even in the darkest pit, he could still see the light coming from above, faint though it appears. He clung to the hope Lulu could rescue him."
    "Days went by, still nothing of note happened. He began wondering if the pain they would inflict on him was as bad as others made it out to be."
    "The last time he heard someone had been whipped seemed to be a lifetime ago."
    "Thinking back when he was a child, he had heard the story that someone down the street had been punished because others had spoken ill of him when he could not prove otherwise."
    "Nabisin’s mother had disapprovingly nodded towards the man, condemning him of being deserving of that kind of punishment."
    "Right now, he couldn’t bear the thought of being hurt by others."
    "Even though he grew accustomed to his preference being frowned upon by many others of his kin, he found refuge in being all by himself. Refuge by hiding in corners and not speaking up."
    "But then, one day, he found someone hiding in his spot. "
# [flashback sequence]
    nvlNar "..."
    nvlNar "He was squinting and contorting himself to penetrate the crevices of his hideout."
    nvlNar "He felt an odd presence, larger than himself. He then noticed an antler peeking out."
    nvlNar "At first, Nabisin thought it would poke out his eye, blinding him."
    nvlNar "He kept at a safe distance. The other boy didn’t react to Nabisin’s presence. Had he been staring at the figure for more than a couple of minutes? He didn’t know."
    nvlNar "They were alike in that they both had to take care of extra head gear that so annoyingly made matters difficult. Entering houses of smaller species was no easy feat."
    nvlNar "It was impressive that both of them could squeeze into that space and reside it for more than a couple hours without feeling the abrasive walls closing in."
    nvl clear 
    nvlNar "Trying to adjust himself to a more comfortable position, Nabisin tried to lean against a brittle wall. As soon as he put half of his weight against it, it collapsed, and he almost hit the ground."
    nvlNar "Awkwardly trying to pretend nothing had happened, one of the deer’s ears raised as he heard the sound of the crumbling bricks and ash rising."
    nvlNar "The figure looked back toward Nabisin, who had hurriedly and awkwardly tried to hide in another part of the ruins. The boy was holding a stick and drawing something in the dirt akin to a circle."
# ???:
    "???" "“Hey, you.”"
    "???" "“I can see your tail.”"
    "Ignoring the spoken word, Nabisin tried to cover his tail."
# ???:
    "???" "“No, don’t hide it silly!”"
    "???" "“It looks silky and cute.”"
# Nabisin:
    n "“Go away.”"
# ???:

    "???" "“Why should I?”"
    "???" "“I’m just here by myself doing nothing.”"
# Nabisin:
    n "“This is my special place.”"
# ???:
    "???" "“Then, let it be our place.”" 
    "???" "“See, I just started something.”" 
    l "“Also, the name’s Luludân.”"
    nvlNar "I’m unsure what Luludân meant by that, but Nabisin felt like helping him."
    nvlNar "A weird aura surrounded the entire place once Nabisin stepped closer, cold but also warm; the lights that bathed the place started to shift and merge as if they were underwater; darkness sometimes made itself greater than light but was quickly overwhelmed by light again."
    nvl clear 
    nvlNar "Something was off. He could hardly recollect all that had happened in the last minute or so. It was as if nothing had happened."
    nvlNar "There was a gap in his memory, one that could never be filled, no matter how hard Nabisin tried to think the first day he met Lulu."
    "He didn’t think ill of his lover; maybe it was just a matter of being young and not remembering much of those times. Memories often get distorted over time."
    "Lulu told Nabisin much later, once they started dating, that he had hit his head trying to hide from him."
    "And sure, Nabisin knew he had almost crumbled as he remembered details of the walls giving up on weight."
    "But, while it seemed easy to dismiss it as just kids being extremely clumsy, Nabisin couldn’t pinpoint the source of why his head later that day felt lighter than ever; maybe a headache had to stroke him, and recollecting the events of their first meeting must’ve been too embarrassing, even to your taste."
    "Trust was blindly put to exercise; Nabisin didn’t think of that day anymore but of the moments that made their relationship real and tangible."
    "Lulu kept on, a bit hesitant, as if he also had trouble recollecting the events of that day. Even so, Nabisin always felt Lulu omitted crucial details in the narrative."
    "He said he ran to Nabisin’s aid, afraid he would die if he got horns injured, something that could aggravate matters."
    "But, something didn’t sit right with that follow up either. If Lulu hadn’t helped him, would he be dead?"
    "It was silly to think of such a thing. Right now, he should focus on something else. Lingering on these thoughts offers no service."
    "There were many things Nabisin didn’t know about Luludân, which was agonizing to some degree, as if Luludân drew lines in their relationship."
    "No, they were always honest with each other; their relationship had no lies, limits, or gaps. It was almost as if he had been under some spell Lulu put him through, but that was unlikely also. Magic was prohibited, and even then the gods would never allow it."
    "He had questioned it for a long time, a persistant nagging thought that he had somehow been under Lulu’s spell, as if it were a strange possibility." 
    "Natural laws couldn’t explain their union and boundless love, but there they were, in bright light, being themselves and loving themselves."
    "A man was designed to be with a woman, or so they were thought to be."
    nvlNar "Luludân was designed for Nabisin, and they were satisfied with their own self-crafted truth. However, the details of that first meeting became murkier as the years passed. "
# [end of flashback]
    "He found himself cornered once again in a different place, one unfamiliar to him. His prison revealed itself in all of its terrifying glory."
    "Pulled out of his thoughts, guards approached his cell."
    "Enormous in stature compared to his modest frame, Nabisin always had to look up as both a sign of respect and honor for their noble job, despite this time keeping an innocent man behind bars."
    "It was no wonder why the entire high echelon up until
the king was only composed of lizards and dragons."
    "But this time, together with them, a familiar muzzle appeared. Although covered in a cloth, Nabisin did a double take at who was approaching with haste and worry."
    "Slowly it dawned on him... that muzzle belonged to a fox he knew quite well..."
    "Wait, Shelibuum!"
    "A menacing aura surrounded them; the guards were
certainly not permitted to let this meeting happen!"
    "Shelibuum must have bribed them to get to me, which meant this case would be difficult."
    "Covered from head to toe, her tail was also curled so as not to announce her presence. Silence once again enveloped both of us. In a way, it was comforting seeing an old friend. She fumbled in the pockets of her attire, taking out a carved statuette with an odd base that refused to remain still."
    "The strange object seemed almost drawn to Nabisin. It shook a little, though that could’ve been Shelibuum’s nervousness getting the best of her. The figurine had no imperfections, bumps, or signs of knife work, either."
    "It has been carved with perfect precision."
    "Examining the object further, Nabisin thought of asking Shelibuum, but she looked into Nabisin’s eyes, which mirrored his soul."
    "Signaling the guards she was done, they quickly scolded her back to outside."
    "Eluded by the statuette’s meaning, or the lack thereof, he pondered who could carve so perfectly like that."
    "The statuette was made of wood, with strange metal intertwining the core and then surfacing in intricate patterns."
    "Maybe another language, Nabisin thought." 
    "Putting the statuette away for a second, he tried to think of many solutions to the enigma." 
    "Suddenly he recognized it; that was Lulu’s art sculpted into a beautiful statuette!"
    "The perfection was beyond any other man’s capacity, only one such as Lulu could’ve made such beautiful statuette with such detail and mindfulness."
    "It was a goat, like him, with its arms outstretched in prayer formation, though now that he examined the statuette, it seemed malleable enough to form any pose."
    "A visible smile cracked onto his face. Nabisin could feel as if the dark corridor he had been so desperately looking for a way out from had become less narrow."
    "I knew it!" #nabisin thinking
    "He’s still after me!"
    "Even though happiness restored Nabisin’s hope, as if he could sense Lulu’s presence in his enclosure, reaching for his chin and caressing his fur, he had more pressing matters."
    "Getting a sign is the first step towards his liberation. Now, the hard part is still to come. He attempted to script how his trial may proceed in his mind."
    "Now that the heavy weight was swiftly lifted, the bed seemed to draw even closer to him. His thoughts were all around the place. It gave himself another excuse to just lay down and forget everything."
    "The chilly night felt a bit warmer that day. The fine, scented breeze reminded Nabisin of his time sleeping at the temple headquarters once he had been initiated as a priest."
    "He was required to live by older priests and his colleagues. A certain someone always tried to bother him at every turn. Speaking up to the higher ones was of no avail, as they seemed to enjoy seeing acolytes being harsh to each other."
    "Sometimes it could be fun. They used to play many silly games, but even when harsher forms of aggression took form, higher-ups still didn’t care."
    "The thick veil of the night was lifted, and sunlight entered through the small crevice in his cell of involuntary imprisonment."
    "Every day he followed the same routine, tiresome as it was. He only had one thing to do: wake up and face the guards."
    "He shouldn’t have become accustomed to being in such a dire state, but he confessed he did out of fear he wouldn’t make it out."
    "Still, yesterday’s spark of change gave Nabisin a reason to hold out long enough for another sigh."
    "Each at their respective spots, the two guards shuffled places. Nabisin assumed much was to come in the following hours."
    "The rusty creak of the cell opening would have been deafening to Nabisin had he not been so anxious about what was going to happen."
    "Being scolded down the corridors that served as his imprisonment, he felt several gushes of air coming his way, damp and breezy. The incense of nearby temples was noticeable to such a degree Nabisin knew today must be the god Shamash’s birthday."
    "A weird stinging sensation across his arms made them incredibly itchy for a moment. His fur felt as if being torn apart by small flames, and his lower legs also felt worse than painful stings." 
    "Then, as if nothing had happened, relief overwhelmed him. The winds settled on him, making it much easier to reassess the situation and check his arms and legs."
    "Unsurprisingly, nothing seemed etched into his fur, as the burning sensation would have indicated. Not a single scratch or patch of fur had been damaged."
    "Was his mind playing some sick trick on him on the way to his trial? Had he done something unusual?"
    "Trying to calm himself, Nabisin remembered the small statuette tucked in his dirty robes."
    "It was the same as yesterday, though some of its metal markings seemed to glisten more than before, reflecting the sun like a crystalline pond."
    "Still trying to decode the meaning of these strange series of events, the statuette felt lighter for a second, as if could move on its own."
    "Then its usual weight came back."
    "If the gods wish to blind me, they can do as they please, but this absurdity needs to end. What in the name of heavens has happened to me?"
    "Had my mind turned into stew for straying away from the gods!"
    "Cursing under his breath, Nabisin was fuming, insecure about his situation, and even more nervous about being falsely accused of a crime he hadn’t committed."
    "Before long, the palace shadow projected onto Nabisin and the guards scolding him. This menacing construction was the House of the Just and where Shulgi, King of the Four Corners of the World resided together with his personnel."  
    "He once visited this place during his years of learning as an acolyte; now he is here as a prisoner."
    show trial 
    "The place was mostly the same as it always had been; nothing new was here beyond the new guards and King Shulgi sitting on his throne."
    "The trial would begin once the scribes arrived at the scene, prompted to either record this legal procedure or to spew and remind the accused person of his crimes."
    "Neither Lulu nor Shelibuum were seen. They were either late or were not invited. This seemed quite strange, given that they also partook in Nabisin’s “crime” so to speak."
    "Out of the corner of his eye, a most unpleasant visage appeared: that of Utudug, the bastard who had made Nabisin’s life a torment. Hadn’t the universe paired them during his time as an acolyte, things could have been considerably different."
    "Trying to control his breath, Nabisin hated Utudug with every fur of his being; he felt more than willing to strangle him and leave him to rot under the Euphrates; may the gods forget he was ever there."
    "The silent hatred behind his facade intoxicated Nabisin’s hot, boiling blood with the most vile poison, so much so that he was crushing Lulu’s gift he had been holding this entire time."
    "His fists crushing the statue with his finger hooves, he should have broken the fragile, shiny metal sculpture, but despite this, the statuette refused to shatter."
    "Instead, it slipped from his hands, and the statuette, as if it had sprung to life, bounced upon the floor, rolling across the room until it stood upright."
    "Nabisin tried to grab the fleeting gift, jumping and spinning, which seemed to have a desire of its own, but once he caught the statuette, it refused to move from its spot, almost as if it was designed to be there."
    "No matter how much force he applied to pull, twist, even knock the statuette over, it was melded to the ground."
# Guard:
    g "“Hey, you there! Get off the ground, mutt. The scribes
are already here.”"
    "Trying not to embarrass himself more, he rose from the ground and went back to his place. He remembered when Shelibuum gave him the statuette and how, even though it had been less than a day, he had given the object emotional significance as a gift, hope, and love."
    "Yet it slipped from his hands as if it were forcibly jerked away, leading him to believe some otherworldly force animated it."
    "He couldn’t understand the meaning of anything that happened within the last days or so." 
    "Remembering long lost memories that both reminded him of happier times of ignorance and the burning sensation that felt as if his skin was being torn apart, yet no signs of cuts. Now add to the list his gift creating a mind of his own and attaching itself to the floor."
    "There was no explanation whatsoever. Being alone again was a mind-numbing experience. He hadn’t been like this for years. He was always by Luludân, and yet right now, he felt as if the world had become a husk of itself. He barely knew what was to come."
    "Suddenly, the room grew wider and taller. Nabisin, at the center, stood still when he saw another familiar muzzle—that of Shelibuum, calming his nerves. At least she was smiling, but soon, she turned her gaze back to her doings."
# Judge:
    "Judge" "“Nabisin, The one who calls upon Sîn, may you be judged with the god’s favor on your side, and may the rivers spare you. We are united here for your offenses towards Utudug, he who is good, towards your unnatural liking for the same as your sex.”"
    "Judge" "“Can you contest these accusations?”"
    "The piercing and demanding voice of the judge cut through the air. Everyone, including Nabisin, was taken back to the memory of that night."
    "The offense was to speak up before a high member of the priests, their favorite in fact, and leave so soon as to displease the high priests who had traveled from far and wide."
    "Nabisin tried to speak; his mouth was gaping open several seconds before he could mutter any word under his breath."
    "Given his anger and almost desperation, he finally spurts some words."
# Nabisin:
    n "“It was not my intention to so disrespect and misbehave as my high rank so demands at the feast.”"
    n "“Utudug has always been a sore pain in my life. From the time we were paired during our training to this very sour day.”"
    "Trying to subdue his anger, he inhaled and exhaled in hopes of simmering down his hateful thoughts. He calmly returned to his monologue."
    n "“If thou hast a problem with what I do with my life, may the gods be in my favor and bring reason to this. It is not your business to force yourself into my affairs and declare my desires to be inappropriate.”"
    n "“Only the gods are to administrate these petty matters. Haven’t you noticed the increasing danger of Euphrates flooding our fields? Of our foodstuffs decaying? It is known our instability has only begun.”"
    "The room fell into a deafening silence; even the judge and Utudug felt conflicted about speaking up again."
    "A dense aura surrounded the place. The air felt quite heavy to breathe, as a thin beam of light appeared to shift and dance. Nabisin felt sweaty for a moment, staring intently toward the statuette that was attached to the floor."
    "No one other than Nabisin noticed the atmosphere around them mutating, manifesting some tempest or solar eclipse. The statuette was too far away, just outside his range of vision to notice the small details. But its silhouette was visible, and it changed its pose." 
    "He couldn’t quite understand what pose it was trying to do or what was happening."
    "His overwhelmed senses were overcome, the last barrier preventing insanity. The ground felt like it was crumbling; he wanted to either vomit or faint. Then just as suddenly, everything subdued, being cut with the Judge’s harsh voice."
# Judge:
    "Judge" "“NABISIN! Are you still with us?”"
# Nabisin:
    n "“Pardon, I may have entered a state of unwellness; my senses were overwhelmed-”"
# Judge:
    "Judge" "“Silence! Your time is over. Utudug, who is good, may you speak?”"
    "His ill intentions bathed his face with contempt, but he stood loosely. Calmness was his mask, and his calculated, condescending gestures and words spit like a cobra’s venom."
# Utudug:
    u "“Well, I know much about our infancy and time spent at the temples, cares, and I didn’t hold such grudges against you, Nabisin. I remind you, our activities were weak, but you grew sour of me and my comrades. How can one speak up for you when you clearly can’t handle a playful shove?”"
    u "“Onto the next matter, your liking is evident; you are feminine. Girl-like. Your taste is vile and that of twisted nature. That’s very much why the gods had passed down the laws we know and exercise on this land, which by your own narrative is being punished by divine intervention or lack thereof.”"
    u "“You are practically a female, Nabisin. {w}Accept it. Dress like one of them; your slender physique reminds me of a slave I once had who married a mutt and managed to become free.\"" 
    u "\"Much to your surprise I’m sure, I’m merciful and have bid them farewell. {w}But if you can’t bear the pains of a man, then fifty blows and becoming a eunuch shall suffice your perverted desires.”"
    "Whispers filled the room left and right. {w}People were sure Utudug was right, but they also discussed the possibility of this going too far." 
    "It’s been three years since the last time someone was beaten and made a eunuch."
    "Sure, things change. People become softer or harder over time, but it has come to the attention that, indeed, there were more pressing matters at the moment. {w}Likewise was what Nabisin had brought to the table."
    "Men can change the laws to better suit their needs, and the last time this happened, people decided it was too harsh a punishment."
    "Nevertheless, Utudug was adamant about his beliefs and spewed his poison everywhere."
    "The judge struggled to reestablish order in the room by speaking up, but his voice refused to reach anyone once the whispers became conversations and conversations became disagreements. But then…"
# Judge:
    "Judge" "“ENOUGH!”"
    "Everyone went quiet, knowing he had the final word on this case. Each of them resented but complied with the call."
    "Not only was Nabisin’s fate given to others to meddle with, but his temper once again started to become increasingly hard to control once he started to stare at the statuette."
    "Time seemed to slow down, and the object he once appreciated seemed to move graciously, painting a pose that Nabisin tried to imitate."
# Judge:
    "Judge" "“It is decided so, Nabisin, you are set to receive fifty
blo-…”" #(text gets progressively small)
    "The voice of the judge started to get muffled as the
room goes silent."
    play music "rolling_stones.mp3" volume 0.6 loop fadein 0.5
    "As the statuette moved, Nabisin stroked another pose mimicking its elusive dance, expecting something, if anything, to happen. {w}He didn’t lose his composure because he knew unless something happened would be soon sentenced to a barbaric punishment that would debilitate him forever."
    "The statuette struck another pose, and Nabisin already knew to follow. Meanwhile, the judge tried to raise his voice once more, and Nabisin ignored him. Locked in a trance-like state, he danced at the statuette’s will as if nothing else mattered."
    play music "stormy.mp3" volume 2 fadein 0.5
    "The image he had hoped to see again flashed before his eyes; the palace descended in chaos, the light sources flickered, and gushes of wind intruded with all kinds of scents."
    play sound "lightning.mp3" volume 3
    "Nabisin didn’t think to connect his dance to the sudden shift in atmosphere. Winds became stronger and stronger, the floor started to shift a little bit, a tempest seemed to form outside, and on cue, it started raining."
    play music "rain.mp3" fadein 0.5
    "Finally, the statuette’s dance seemed to reach its eventual end. The symphony of screams, chaotic shuffling, and Utudug bracing himself in terror before being thrown at a wall was probably the best scene Nabisin could imagine, and it was happening right before his eyes."
    stop music
    play sound "earthquake.mp3"
    "Was he doing all of that by following the movements? Was it magic? Some sort of favor of the gods? Or just a coincidence? As he struck the final pose, he didn’t know or seek to question further." 
    "With it, time seemed to return to its natural flow, but something awful was bound to happen."
    "Ripples through the ground grew steadily; the judge seemed to struggle enough to hold himself upright. Meanwhile, Nabisin barely felt his feet shuffle. He was still waiting for the statuette to act more than create some cracks for his accusors to stumble upon." 
    play sound "exploding.mp3"
    show dust with Dissolve(1)
    "Suddenly, with the tremor of an earthquake, the palace crumbled upon itself, brick by brick falling.The structure was barely holding itself, revealing a giant hole that engulfed everyone around Nabisin. The absolute horror on his face was notable, but he felt they earned their judgment."
    "Perhaps not everyone deserved the fate of getting swallowed by the bowels of the Earth, perhaps even the judge, but now the hole was getting bigger and bigger." 
    "He wasn’t sure whether Shelibuum left the room in time; all he knew was that the place had become a husk of itself. {w}And he was standing in an unaffected pillar, a single section that had not crumbled."
    "There’s no doubt that that was beyond what Nabisin knew. {w}Could he even call that magic? Maybe it was the craft of a god in his favor, but the statue suggested that he himself had done it. "
    "No matter how much he wanted to believe it was an external factor, he somehow did that, and in the process he killed Utudug, the very man who wanted to see him frail and devoid of life."
    "By the time the earthquake subsided, Nabisin thought to himself. I guess that’s it, but where do I go from here?"
    "Quietness overcame the echoing sounds of crumbling bricks and cracks opening. {w}Out of the mud that became the floor, a monster shouted at the top of his lungs. {w}A hand stuck out, and then the muzzle of a gray cat once called Utudug came into view."
# Utudug:
    u "“YOU! GRNNRNNRNANNGNGNNARHA!”"
    u "“You’re going to pay for this, girl-like abomination on the face of the gods. May you die painfully under the rivers-”"
    "His distorted face of hatred and vengeance was all that Nabisin could see as Utudug rapidly became snail- like, his legs had been crushed by the earthquake he had summoned."
    "Then, it came to Nabisin he needed to do this. {w}He wanted to. As much as kindness and reciprocity was his motif, his anger overwhelmed all other senses."
    "No one should be subjected to having their life threatened in this manner." 
    "Nabisin landed a swift kick to Utudug’s face, after which he fell into another puddle of mud. {w}It soon succumbed to his weight and impact, swallowing the demon with a catlike disguise."
    "He was finally gone for good, and as much Nabisin felt tired and dirty, he felt like he had stood up to all the bad people in his life and literally kicked the worst of them all in the face."
    "Tired and feeling quite limp, he fell to his knees after such eventful evening. {w}The setting sun kissed his face with its array of yellow, orange and red colors while the sky displayed an even more beautiful array that made every moment of hell he had recently experienced somehow worth it."
    "Freedom. {w}Nabisin was liberated from the shackles of those who were against him. He didn’t care whether he had ended an entire dynasty or somehown ended the lives of people who were going to kill him anyway."
    "He only craved what many had, but was forbidden to have because of his own liking for the male build ... the all the curves and features of a male body, all of the symbolism and mundaneness of being a male and desiring men."
    show sunset with dissolve
    "A cool breeze washed over his body, giving the sensation of freshness after a bath. He had longed for that for days."
    "Now to other nagging questions. {w}He thought of Luludân his love, and where was he, what he had done, what would happen to both of them." 
    "If only being by his side meant everything was going to be just fine..."
    "On the horizon, just before the sun set to be replaced by the veil of night, a figure similar of Luludân stood up. {w}He was holding up his arm, waving his hand erratically, waiting to be noticed."
    "The crumbled mess between the two made things quite difficult, but once Nabisin managed to climb out of his little altar, he ran for the man he had craved, missed and desired for so long, not caring whether he was stepping on ground that could collapse and swallow him up." 
    "Finally, a tearful Nabisin was met with the caring arms of Luludân."
    "Once their bodies met in sweet embrace, everything else became a blur. {w}Right now they couldn’t be separated, even by the strongest force in the universe, their love was boundless, especially now when they haven’t seen each other for days."
    "The wind settled down, the sun rested beyond the horizon, and they both cried upon each other’s arms."
# Nabisin:
    n   "“I-, I missed you greatly.”"
    "Sheepishly admitting to Luludân, Nabisin took hold of his muzzle analyzing each and every detail of his features." 
    "Soon they both kissed and caressed each other. {w}Luludân however moved his hand discretely. A few pillars shifted, raising them up above the ruins."
    "As the night settled in, they cuddled until one of them broke the silence with a simple question."
# Nabisin:
    n   "“Where do we go from here now?”"
# Luludân:
    l   "“{cps=2}...{/cps}”"
    l   "“I know, its always been like this since we met, but
there’s something I need to tell you...”"
scene black with dissolve
$persistent.chapter_2 = True
return 